
### Obtener todos los personajes
GET http://localhost:3000/api/personajes


### Obtener un personaje

GET http://localhost:3000/api/personajes/bd1279bb-71dd-4ed7-9e3d-bb3c8a9cc6df

### Subir personaje

POST http://localhost:3000/api/personajes
Content-Type: application/json

{
    "name": "Ahsoka",
    "characterClass": "Jedi",
    "items": ["Espada laser"],
    "attack": 10,
    "level":40,
    "hp": 900,
    "mana":750
}

### Actualizar personaje con PUT

PUT http://localhost:3000/api/personajes/943434ad-be3b-4833-b564-8b6dba873765
Content-Type: application/json

{
    "name": "Obi-wan", 
    "characterClass": "Jedi",
    "items": ["Espada laser"],
    "attack": 40,
    "level":100,
    "hp": 1500,
    "mana":1200
}

### Actualizar personaje con PATCH (parcialmente)

PATCH http://localhost:3000/api/personajes/943434ad-be3b-4833-b564-8b6dba873765
Content-Type: application/json

{

    "attack": -5,
    "level":5,
    "hp": 5

}

### Delete de un personaje por ID
DELETE  http://localhost:3000/api/personajes/eab222aa-b70e-48fe-9798-cec3b412c568
