
### Obtener todos los personajes
GET http://localhost:3000/api/personajes


### Obtener un personaje

GET http://localhost:3000/api/personajes/b185c894-4dc9-450c-a83b-43b75c9b1662

### Subir personaje

POST http://localhost:3000/api/personajes
Content-Type: application/json

{
    "name": "Ahsoka",
    "characterClass": "Jedi",
    "items": ["Espada laser"],
    "attack": 10,
    "level":40,
    "hp": 900,
    "mana":750
}

### Actualizar personaje con PUT

PUT http://localhost:3000/api/personajes/c2aba397-749f-4418-89e5-5754c25b1f0e
Content-Type: application/json

{
    "name": "Obi-wan", 
    "characterClass": "Jedi",
    "items": ["Espada laser"],
    "attack": 40,
    "level":100,
    "hp": 1500,
    "mana":1200
}

### Actualizar personaje con PATCH (parcialmente)

PATCH http://localhost:3000/api/personajes/411ab848-c346-4b72-a1a3-352b29412a22
Content-Type: application/json

{

    "attack": -5,
    "level":5,
    "hp": 5

}

### Delete de un personaje por ID
DELETE  http://localhost:3000/api/personajes/a818f5c2-cdf8-44b6-a63c-262381a63531
